# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 389e7d1c02bdeb25f9f3a072cfd3111a3b9ff6d88a2c72feb060da87f216693c28bc7b1b446b34f2b85000121ed46838bdfb97a5b18af783191350bbd4e244f5

test:
  secret_key_base: f1c4764c83973b0dd3890d1556ef4d0dd1b205632794b691dfbb5863dc283f00def21ee2de2a1618d469412b9315a7c631b97cc4df4ae45a5a12f622a9ed5c5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
